language: php

matrix:
  fast_finish: true

  include:
    - os: linux
      php: '7.1'
      env: DISABLE_XDEBUG="true"

    - os: linux
      php: '7.2'
      env: PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml"

    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - _OSX=10.11
        - _PHP: php71

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then /usr/bin/env bash bin/prepare_osx_env.sh ; fi
  - if [[ DISABLE_XDEBUG == "true" ]]; then phpenv config-rm xdebug.ini; fi

install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then /usr/bin/env bash bin/handle_brew_pkg.sh "${_PHP}" ; fi
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction --ignore-platform-reqs

script:
  - bin/phpunit $PHPUNIT_FLAGS

after_success:
  - |
    if [[ $PHPUNIT_FLAGS != "" ]]; then
      php bin/coveralls -v
    fi
